sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t smdasim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smdasim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-361808305504'

  bucket_path: 'docker-react'
  on:
    branch: feature
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
